model:
    type: "resnet18"

dataset:
    data_dir: "./data/ms1m-retinaface-t1" 
    num_classes: 93431
    num_image: 5179510

dataloader:
    batch_size: 64
    num_workers: 8

pipeline:
    Trainer:
        grad_norm_clip: -1.0
        ckpt_interval: 5
        eval_interval: 5
        epoch: 40

    Optim:
        scheduler_kwargs:
            epoch0: 0
            epoch1: 40
            lr0: 1.e-3
            lr1: 1.e-6

    Logger:
        log_dir: "./logs/"
        tag: "learn_arcface"
        log_fname: "log.txt"
        backup_list: []

    


