model:
    type: "detr"
    kwargs:
        dropout: -0.5
        num_pts: 56
        embedding_length: 128
        window_size: 11
        # focal_loss_gamma: 0.0

dataset:
    augment_data: False
    person_only: True

    DataHandle:
        data_dir: "./data/JRDB"  # ./data/JRDB or ./data/DROWv2-data
        num_scans: 1
        scan_stride: 1
        tracking: True

    cutout_kwargs:
        fixed: False
        centered: True
        window_width: 1.0
        window_depth: 0.5
        num_cutout_pts: 56
        padding_val: 29.99
        area_mode: True

dataloader:
    batch_size: 4
    num_workers: 4

pipeline:
    Trainer:
        grad_norm_clip: -1.0
        ckpt_interval: 50000
        eval_interval: 1
        epoch: 40

    Optim:
        scheduler_kwargs:
            epoch0: 0
            epoch1: 40
            lr0: 1.e-3
            lr1: 1.e-3

    Logger:
        log_dir: "./logs/"
        tag: "drow_jrdb_detr"
        log_fname: "log.txt"
        backup_list: []

    


